- name: Obtain wildcard SSL certificate with Let's Encrypt
  hosts: all
  become: yes
  user: root

  vars_files:
    - ../env.yml

  vars:
    email: "{{ LETS_ENCRYPT_EMAIL }}"
    domain: "{{ APP_MAIN_DOMAIN }}"
    domains: "-d '{{ APP_MAIN_DOMAIN }}' -d '*.{{ APP_MAIN_DOMAIN }}'"

  tasks:
    - name: Install Certbot
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx  # Optional if using Nginx
        state: present
        update_cache: yes
      become: yes

    - name: Generate wildcard SSL certificate (manual DNS challenge)
      ansible.builtin.command:
        cmd: >
          certbot certonly --manual
          --preferred-challenges dns
          --server https://acme-v02.api.letsencrypt.org/directory
          --agree-tos
          -m {{ LETS_ENCRYPT_EMAIL }}
          -d "*.{{ APP_MAIN_DOMAIN }}"
          -d {{ APP_MAIN_DOMAIN }}
        creates: /etc/letsencrypt/live/{{ APP_MAIN_DOMAIN }}/fullchain.pem
      register: certbot_output
      ignore_errors: yes

    - name: Display Certbot instructions
      ansible.builtin.debug:
        msg: "{{ certbot_output.stdout }}"
